// Generated by iara-opt VirtualFIFOSchedulerPass. Do not edit.
#ifndef IARA_RUNTIME_CONFIG_H
#define IARA_RUNTIME_CONFIG_H
// semaphore = sharded-hash
#define IARA_SEMAPHORE_SHARDED_HASH 1
// alloc_mode = data-triggered
#define IARA_DATA_TRIGGERED_ALLOC 1
// broadcast borrow = on
#define IARA_BROADCAST_BORROW 1
#endif // IARA_RUNTIME_CONFIG_H
