export IARA_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export PROJECTS_DIR="$(dirname "$IARA_DIR")"

echo -n 'Loading modules... '
# Pin cmake to the spack module 3.31.4, NOT bare `cmake`. Bare `module load cmake`
# resolves to the OpenHPC default (cmake/4.3.2), whose binary NEEDs libjsoncpp.so.25.
# That system lib exists on the login node but is ABSENT on the Slurm compute nodes,
# so every compute-node build died with "libjsoncpp.so.25: cannot open shared object
# file". The spack cmake/3.31.4 has no such dependency and works on both. (This is the
# same cmake .env.cached captured; pinning keeps sorgan_env.sh in sync with it.)
module load casacore cmake/3.31.4 ccache cuda gdb/15.2 openblas python/3.13 mold gcc/14.2 abseil-cpp valgrind

echo -n 'sourcing spack... '
# Override global spack (v0.24.0 from /etc/profile.d) with local version
source "$IARA_DIR/spack/share/spack/setup-env.sh"
spack env activate iara_env

echo -n 'Loading more modules... '
module load casacore cmake/3.31.4 ccache cuda gdb/15.2 openblas python/3.13 mold gcc/14.2 abseil-cpp valgrind

# cmake/3.31.4 pin (see note above): the bare `cmake` default is ohpc 4.3.2, broken on compute nodes.
for i in gdb gcc ninja cmake/3.31.4 ccache casacore abseil-cpp mold valgrind python/3.13.1 openblas; do
  module load $i
done

echo -n 'nvm... '
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"
nvm use v25.6.1 > /dev/null 2>&1

echo -n 'venv... '
VENV_DIR="$IARA_DIR/.venv"

if [ ! -d "$VENV_DIR" ]; then
  echo "Creating Python virtual environment in $VENV_DIR..."
  python3 -m venv "$VENV_DIR"
  source "$VENV_DIR/bin/activate"
  pip install --upgrade pip
  pip install -r "$IARA_DIR/requirements.txt"
else
  source "$VENV_DIR/bin/activate"
fi

# --- Environment variables (formerly in .env / generated by scripts/generate_env.sh) ---

echo -n 'Setting env vars... '

export LLVM_SOURCES="$PROJECTS_DIR/clangir"
export LLVM_INSTALL="$PROJECTS_DIR/llvm-install"
export LLVM_BUILD="$LLVM_SOURCES/build"

export PATH="$IARA_DIR/scripts:$LLVM_INSTALL/bin:$IARA_DIR/build/bin:$LLVM_SOURCES/build/bin:$PATH"
export PYTHONPATH="$IARA_DIR:$PYTHONPATH"
export PS1="(iara)$PS1"

SPACK_VIEW_PATH="$IARA_DIR/spack/var/spack/environments/iara_env/.spack-env/view"
export SPACK_VIEW_PATH
export C_INCLUDE_PATH="$SPACK_VIEW_PATH/include:$C_INCLUDE_PATH"
export CPLUS_INCLUDE_PATH="$SPACK_VIEW_PATH/include:$CPLUS_INCLUDE_PATH"
export LIBRARY_PATH="$SPACK_VIEW_PATH/lib:$LIBRARY_PATH"
export LD_LIBRARY_PATH="$SPACK_VIEW_PATH/lib:$LLVM_INSTALL/lib:$LLVM_INSTALL/lib/x86_64-unknown-linux-gnu:$LD_LIBRARY_PATH"
export PKG_CONFIG_PATH="$SPACK_VIEW_PATH/lib/pkgconfig:$PKG_CONFIG_PATH"
export LDFLAGS="-L$SPACK_VIEW_PATH/lib $LDFLAGS"

export PREESM_DIR="/scratch/$USER/bin/preesm-dir"
export PREESM_DEGRIDDER_REPO="/scratch/$USER/repos/preesm-apps/degridder"
export PREESM_SIFT_REPO="/scratch/$USER/repos/preesm-apps/SIFT"
export JAVA_HOME="/scratch/$USER/bin/java-17"
export PATH="$JAVA_HOME/bin:$PATH"

# Keep the project venv first on PATH: the spack `python/3.13` module and the
# later PATH prepends above otherwise shadow the venv interpreter, so `python3`
# resolves to spack python (no yaml / project deps). Do this last so nothing
# can push the venv back down.
export PATH="$VENV_DIR/bin:$PATH"

# SACI (Scheduler-Agnostic Continuous Instrumentation) Slurm configuration
export SACI_SLURM_NODE_LIST="sorgan-cpu[1-4]"

# Tab completion for the experiment framework CLI
if command -v register-python-argcomplete &>/dev/null; then
  eval "$(register-python-argcomplete "python3 -m tools.experiment_framework")"
fi

echo 'Done!'
