#!/usr/bin/env python3
"""
Verification script for Task 1.4 - CMakeLists.txt Generation

This script demonstrates that all three functions work correctly and produce
valid output according to the specification.
"""

import sys
from pathlib import Path
from tools.experiment_framework.generator import (
    generate_instance_name,
    generate_cmake_instance,
    generate_cmakelists,
)
from tools.experiment_framework.config import load_experiments_yaml

def verify_instance_naming():
    """Verify instance naming convention"""
    print("\n" + "="*70)
    print("VERIFICATION 1: Instance Naming Convention")
    print("="*70)

    test_cases = [
        {
            'app': '05-cholesky',
            'params': {'scheduler': 'vf-omp', 'matrix_size': 2048, 'num_blocks': 2, 'block_size': 1024},
            'computed': {'block_size'},
            'expected': '05-cholesky_vf-omp_matrix_size_2048_num_blocks_2'
        },
        {
            'app': '08-sift',
            'params': {'scheduler': 'sequential', 'image_height': 640, 'image_width': 800},
            'computed': set(),
            'expected': '08-sift_sequential_image_height_640_image_width_800'
        },
    ]

    for i, test in enumerate(test_cases, 1):
        name = generate_instance_name(test['app'], test['params'], test['computed'])
        status = "✓ PASS" if name == test['expected'] else "✗ FAIL"
        print(f"\n{status} Test {i}:")
        print(f"  Application: {test['app']}")
        print(f"  Parameters: {test['params']}")
        print(f"  Generated:  {name}")
        print(f"  Expected:   {test['expected']}")


def verify_cmake_instance_generation():
    """Verify CMake instance code generation"""
    print("\n" + "="*70)
    print("VERIFICATION 2: CMake Instance Generation")
    print("="*70)

    config = {
        'application': {
            'name': '05-cholesky',
            'entry': '05-cholesky',
            'build': {
                'extra_linker_args': ['-lopenblas'],
                'defines': ['VERBOSE'],
            }
        },
        'execution': {'timeout': 300},
        'computed_parameters': [{'name': 'block_size'}],
    }
    params = {
        'scheduler': 'vf-omp',
        'matrix_size': 2048,
        'num_blocks': 2,
        'block_size': 1024,
    }
    instance_name = "05-cholesky_vf-omp_matrix_size_2048_num_blocks_2"

    code = generate_cmake_instance(instance_name, params, config, "regression")

    # Verify key fields are present
    checks = [
        ('NAME field', f'NAME "{instance_name}"'),
        ('EXPERIMENT_SET', 'EXPERIMENT_SET "regression"'),
        ('ENTRY', 'ENTRY "05-cholesky"'),
        ('SCHEDULER', 'SCHEDULER "vf-omp"'),
        ('APPLICATION_DIR', '${CMAKE_CURRENT_SOURCE_DIR}/../..'),
        ('PARAMETERS field', 'PARAMETERS'),
        ('BUILD_DIR', '${CMAKE_BINARY_DIR}/05-cholesky/regression/'),
        ('DEFINES', 'DEFINES'),
        ('SCHEDULER_IARA', 'SCHEDULER_IARA'),  # vf-* → SCHEDULER_IARA
        ('LINKER_ARGS', 'LINKER_ARGS "-lopenblas"'),
        ('TIMEOUT', 'TIMEOUT "300"'),
    ]

    print(f"\nGenerated CMake Code (first 25 lines):")
    lines = code.split('\n')
    for i, line in enumerate(lines[:25], 1):
        print(f"  {i:2d}: {line}")

    print(f"\nField Verification:")
    all_passed = True
    for check_name, check_value in checks:
        passed = check_value in code
        status = "✓" if passed else "✗"
        print(f"  {status} {check_name}: {check_value[:50]}...")
        if not passed:
            all_passed = False

    return all_passed


def verify_cmakelists_generation():
    """Verify full CMakeLists.txt generation"""
    print("\n" + "="*70)
    print("VERIFICATION 3: Full CMakeLists.txt Generation")
    print("="*70)

    yaml_path = Path('/scratch/pedro.ciambra/repos/iara/applications/05-cholesky/experiment/experiments.yaml')

    if not yaml_path.exists():
        print(f"\nSKIPPED: {yaml_path} does not exist")
        return False

    import tempfile
    with tempfile.TemporaryDirectory() as tmpdir:
        output_path = Path(tmpdir) / 'CMakeLists.txt'

        # Generate CMakeLists.txt
        count = generate_cmakelists(yaml_path, output_path, "regression")

        print(f"\nGeneration Summary:")
        print(f"  Application: 05-cholesky")
        print(f"  Experiment Set: regression")
        print(f"  Instances Generated: {count}")
        print(f"  Output File: {output_path}")
        print(f"  File Exists: {output_path.exists()}")

        if not output_path.exists():
            print("  ✗ FAIL: Output file not created")
            return False

        content = output_path.read_text()

        # Verify header
        print(f"\nHeader Verification:")
        header_checks = [
            ('Auto-generated marker', 'Auto-generated by tools.experiment_framework.generator'),
            ('Source path', 'applications/05-cholesky/experiment/experiments.yaml'),
            ('Experiment set name', 'Experiment Set: regression'),
            ('Generated timestamp', 'Generated:'),
            ('YAML hash', 'YAML Hash:'),
            ('DO NOT EDIT', 'DO NOT EDIT'),
        ]

        all_passed = True
        for check_name, check_value in header_checks:
            passed = check_value in content
            status = "✓" if passed else "✗"
            print(f"  {status} {check_name}")
            if not passed:
                all_passed = False

        # Verify CMake structure
        print(f"\nCMake Structure Verification:")
        structure_checks = [
            ('cmake_minimum_required', f'cmake_minimum_required(VERSION 3.20)'),
            ('include statement', 'include(${CMAKE_SOURCE_DIR}/cmake/IaRaApplications.cmake)'),
            ('iara_add_test_instance calls', f'iara_add_test_instance'),
        ]

        for check_name, check_value in structure_checks:
            count_found = content.count(check_value)
            if check_name == 'iara_add_test_instance calls':
                expected = count
                passed = count_found == expected
                print(f"  {'✓' if passed else '✗'} {check_name}: {count_found} (expected {expected})")
            else:
                passed = check_value in content
                print(f"  {'✓' if passed else '✗'} {check_name}")
            if not passed:
                all_passed = False

        # Show sample instance
        print(f"\nSample Generated Instance (lines 12-25):")
        lines = content.split('\n')
        for i, line in enumerate(lines[11:25], 12):
            print(f"  {i:2d}: {line}")

        return all_passed


def main():
    """Run all verification tests"""
    print("\n" + "="*70)
    print("Task 1.4 - CMakeLists.txt Generation Verification")
    print("="*70)

    verify_instance_naming()
    cmake_ok = verify_cmake_instance_generation()
    cmakelists_ok = verify_cmakelists_generation()

    # Final summary
    print("\n" + "="*70)
    print("VERIFICATION SUMMARY")
    print("="*70)
    print("✓ Instance naming convention verified")
    print(f"{'✓' if cmake_ok else '✗'} CMake instance generation verified")
    print(f"{'✓' if cmakelists_ok else '✗'} Full CMakeLists.txt generation verified")
    print("="*70 + "\n")

    return 0 if (cmake_ok and cmakelists_ok) else 1


if __name__ == '__main__':
    sys.exit(main())
