"""Data loading and transform evaluation for Vega-Lite specs.

Resolves ``data.url`` references (file://, relative paths) and applies
Vega-Lite transform operators (calculate, filter, fold).
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Dict, List, Optional
from urllib.parse import urlparse


def resolve_data(spec: dict, spec_dir: Path | None = None) -> dict:
    """Resolve the data URL in a Vega-Lite spec and return the loaded data.

    Args:
        spec: Vega-Lite spec dict (may have data at top level or in facet).
        spec_dir: Directory the .vl.json file lives in (for relative paths).

    Returns:
        The loaded data dict (e.g., the full results JSON).

    Raises:
        FileNotFoundError: If the data file cannot be found.
        json.JSONDecodeError: If the data file is not valid JSON.
    """
    data_ref = spec.get("data")
    if data_ref is None:
        # Check inside facet spec
        facet = spec.get("facet")
        if isinstance(facet, dict):
            data_ref = facet.get("data")
    if data_ref is None:
        # Check inside hconcat
        for panel in spec.get("hconcat", []):
            data_ref = panel.get("data")
            if data_ref:
                break

    if data_ref is None:
        raise ValueError("No data.url found in Vega-Lite spec")

    url = data_ref.get("url", "")
    if not url:
        raise ValueError("data.url is empty")

    # Resolve file path
    file_path = _resolve_url(url, spec_dir)

    with open(file_path, "r") as f:
        data = json.load(f)

    # Extract property if specified
    fmt = data_ref.get("format", {})
    prop = fmt.get("property") if isinstance(fmt, dict) else None
    if prop:
        data = data.get(prop, data)

    return data


def _resolve_url(url: str, spec_dir: Path | None) -> Path:
    """Resolve a Vega-Lite data URL to a local filesystem path."""
    parsed = urlparse(url)
    if parsed.scheme in ("", "file"):
        p = Path(parsed.path) if parsed.scheme == "file" else Path(url)
        if p.is_absolute():
            return p
        if spec_dir:
            return (spec_dir / p).resolve()
        return p.resolve()
    raise ValueError(f"Unsupported URL scheme: {parsed.scheme}")


def apply_transforms(data: List[dict], transforms: List[dict]) -> List[dict]:
    """Apply Vega-Lite transform operators to a list of data rows.

    Supported transforms:
        - ``calculate``: Evaluate an expression, append computed field.
        - ``filter``: Evaluate a predicate, keep matching rows.
        - ``fold``: Unpivot columns into key-value pairs.

    Args:
        data: List of data rows (dicts).
        transforms: Vega-Lite transform specifications.

    Returns:
        Transformed list of data rows.
    """
    rows = list(data)  # shallow copy — each row is a dict

    for tx in transforms:
        if "calculate" in tx:
            rows = _apply_calculate(rows, tx["calculate"], tx.get("as", ""))
        elif "filter" in tx:
            rows = _apply_filter(rows, tx["filter"])
        elif "fold" in tx:
            rows = _apply_fold(rows, tx["fold"], tx.get("as", ["key", "value"]))
        # Unknown transforms are silently ignored

    return rows


# ── Expression evaluator ──────────────────────────────────────────

# Minimal JS-like expression evaluator. Supports only the subset
# generated by the experiment framework's visualizer.py.


def _eval_expr(expr: str, datum: dict) -> Any:
    """Evaluate a Vega-Lite expression against a datum row.

    Supports:
        - ``datum.field`` — field access (dot notation)
        - ``datum['field']`` — bracket field access
        - ``replace(str, pattern, replacement)`` — regex replace
        - ``format(value, spec)`` — d3-format-like (delegates to Python)
        - ``toNumber(x)`` — string→float coercion
        - String/numeric literals
        - Arithmetic: +, -, *, /
    """
    # Normalize whitespace
    expr = expr.strip()

    # datum.field access
    datum_match = re.match(r"^datum\.(\w[\w.]*)$", expr)
    if datum_match:
        return _deep_get(datum, datum_match.group(1))

    # datum['field'] access
    datum_bracket = re.match(r"^datum\['([^']+)'\]$", expr)
    if datum_bracket:
        return datum.get(datum_bracket.group(1))

    # replace(datum.field, /pattern/, "replacement") — regex form
    replace_match = re.match(
        r"^replace\((.+),\s*/(.+?)/,\s*['\"](.*)['\"]\s*\)$", expr
    )
    if replace_match:
        inner = _eval_expr(replace_match.group(1), datum)
        pattern = replace_match.group(2)
        replacement = replace_match.group(3)
        return re.sub(pattern, replacement, str(inner))

    # replace(datum.field, 'literal', "replacement") — string form
    replace_str = re.match(
        r"""^replace\((.+),\s*['"]([^'"]*)['"],\s*['"](.*)['"]\s*\)$""", expr
    )
    if replace_str:
        inner = _eval_expr(replace_str.group(1), datum)
        literal = replace_str.group(2)
        replacement = replace_str.group(3)
        return str(inner).replace(literal, replacement)

    # format(value, ".2s") or similar
    format_match = re.match(r"^format\((.+),\s*['\"]([^'\"]+)['\"]\s*\)$", expr)
    if format_match:
        inner = _eval_expr(format_match.group(1), datum)
        spec = format_match.group(2)
        return _d3_format(inner, spec)

    # toNumber(x)
    tonumber_match = re.match(r"^toNumber\((.+)\)$", expr)
    if tonumber_match:
        inner = _eval_expr(tonumber_match.group(1), datum)
        try:
            return float(inner)
        except (ValueError, TypeError):
            return 0.0

    # Arithmetic: simple case for sort_key expressions
    # e.g., "a * 1000 + b"
    # Replace known sub-expressions first, then eval.
    try:
        # Try as numeric literal
        return float(expr)
    except ValueError:
        pass

    # String literal
    str_match = re.match(r"^['\"](.*)['\"]$", expr)
    if str_match:
        return str_match.group(1)

    # Fallback: try to evaluate arithmetic with datum substitution
    return _eval_arithmetic(expr, datum)


def _eval_arithmetic(expr: str, datum: dict) -> Any:
    """Evaluate arithmetic expressions with datum field references.

    Replaces ``datum.field`` and ``toNumber(datum.field)`` references
    with their numeric values, then evaluates the resulting Python
    expression. The compiled bytecode is NOT cached — expressions
    vary per-spec and the overhead is negligible for our scale.
    """
    # Replace toNumber(datum['field']) with numeric values
    safe = expr

    # toNumber(datum['field'])
    for m in re.finditer(r"toNumber\(datum\['([^']+)'\]\)", safe):
        val = float(datum.get(m.group(1), 0) or 0)
        safe = safe.replace(m.group(0), repr(val))

    # toNumber(datum.field)
    for m in re.finditer(r"toNumber\(datum\.(\w+)\)", safe):
        val = float(datum.get(m.group(1), 0) or 0)
        safe = safe.replace(m.group(0), repr(val))

    # datum.field (numeric only)
    for m in re.finditer(r"datum\.(\w+)", safe):
        val = datum.get(m.group(1), 0)
        safe = safe.replace(m.group(0), repr(val))

    # datum['field']
    for m in re.finditer(r"datum\['([^']+)'\]", safe):
        val = datum.get(m.group(1), 0)
        safe = safe.replace(m.group(0), repr(val))

    try:
        return eval(safe, {"__builtins__": {}}, {})
    except Exception:
        return expr


def _deep_get(d: dict, path: str) -> Any:
    """Get a nested dict value by dot-separated path."""
    keys = path.split(".")
    val: Any = d
    for k in keys:
        if isinstance(val, dict):
            val = val.get(k)
        else:
            return None
    return val


def _d3_format(value: Any, spec: str) -> str:
    """Minimal d3-format-like formatting.

    Supports:
        - ``.2s`` — SI-prefix with 2 significant digits
        - ``.1f`` — Fixed with 1 decimal
        - ``.0f`` — Integer
        - ``d`` — Integer
    """
    try:
        v = float(value)
    except (ValueError, TypeError):
        return str(value)

    if spec.endswith("s"):
        # SI prefix
        digits = int(spec[1:-1]) if len(spec) > 2 else 2
        return _si_format(v, digits)
    elif spec.endswith("f"):
        digits = int(spec[1:-1]) if len(spec) > 2 else 0
        return f"{v:.{digits}f}"
    elif spec == "d":
        return f"{int(v)}"
    return str(value)


def _si_format(value: float, digits: int) -> str:
    """Format a number with SI prefix (k, M, G, T, etc.)."""
    if value == 0:
        return "0"
    prefixes = [
        (1e-24, "y"), (1e-21, "z"), (1e-18, "a"), (1e-15, "f"),
        (1e-12, "p"), (1e-9, "n"), (1e-6, "µ"), (1e-3, "m"),
        (1, ""),
        (1e3, "k"), (1e6, "M"), (1e9, "G"), (1e12, "T"),
        (1e15, "P"), (1e18, "E"), (1e21, "Z"), (1e24, "Y"),
    ]
    abs_val = abs(value)
    for threshold, prefix in reversed(prefixes):
        if abs_val >= threshold:
            scaled = value / threshold
            return f"{scaled:.{digits}g}{prefix}"
    return f"{value:.{digits}g}"


# ── Transform implementations ─────────────────────────────────────


def _apply_calculate(rows: List[dict], expr: str, alias: str) -> List[dict]:
    """Apply a calculate transform."""
    for row in rows:
        row[alias] = _eval_expr(expr, row)
    return rows


def _apply_filter(rows: List[dict], predicate: str) -> List[dict]:
    """Apply a filter transform.

    The predicate can be:
        - A Vega-Lite filter expression string (e.g., ``"datum.field == value"``)
        - A dict with ``{field, equal, oneOf, range}`` (Vega-Lite filter object)

    We support the string form (used by the experiment framework).
    """
    result = []
    for row in rows:
        if _eval_filter(predicate, row):
            result.append(row)
    return result


def _eval_filter(predicate: str, datum: dict) -> bool:
    """Evaluate a filter predicate string against a datum.

    Supports: ``datum.field == value``, ``datum.field != value``,
    ``datum.field < value``, ``datum.field > value``.
    """
    # datum['field'] == value
    m = re.match(
        r"^datum\['([^']+)'\]\s*(==|!=|<|>|<=|>=)\s*(.+)$",
        predicate
    )
    if m:
        field = m.group(1)
        op = m.group(2)
        rhs_str = m.group(3).strip()
        lhs = datum.get(field)
        rhs = _parse_literal(rhs_str)
        return _compare(lhs, op, rhs)

    # datum.field == value
    m = re.match(
        r"^datum\.(\w+)\s*(==|!=|<|>|<=|>=)\s*(.+)$",
        predicate
    )
    if m:
        field = m.group(1)
        op = m.group(2)
        rhs_str = m.group(3).strip()
        lhs = datum.get(field)
        rhs = _parse_literal(rhs_str)
        return _compare(lhs, op, rhs)

    return True  # Unknown predicate → include row


def _parse_literal(s: str) -> Any:
    """Parse a literal value from a filter expression."""
    s = s.strip()
    # Number
    try:
        if "." in s:
            return float(s)
        return int(s)
    except ValueError:
        pass
    # String
    if (s.startswith("'") and s.endswith("'")) or \
       (s.startswith('"') and s.endswith('"')):
        return s[1:-1]
    # Boolean
    if s.lower() == "true":
        return True
    if s.lower() == "false":
        return False
    return s


def _compare(lhs: Any, op: str, rhs: Any) -> bool:
    """Compare two values with a given operator."""
    if op == "==":
        return lhs == rhs
    if op == "!=":
        return lhs != rhs
    if op == "<":
        return lhs < rhs
    if op == ">":
        return lhs > rhs
    if op == "<=":
        return lhs <= rhs
    if op == ">=":
        return lhs >= rhs
    return True


def _apply_fold(rows: List[dict], fields: List[str],
                as_names: List[str]) -> List[dict]:
    """Apply a fold (unpivot) transform.

    Args:
        rows: Input rows.
        fields: Column names to fold (supports dot notation for nested access).
        as_names: [key_column, value_column] names for output.

    Returns:
        Expanded rows (one per input row × field).
    """
    key_col, val_col = as_names if len(as_names) >= 2 else ("key", "value")
    result = []
    for row in rows:
        for field in fields:
            new_row = dict(row)
            new_row[key_col] = field
            new_row[val_col] = _deep_get(row, field)
            result.append(new_row)
    return result
