# export EXTRA_KERNEL_ARGS='-DNUM_BLOCKS=4 -DMATRIX_SIZE=8192 -DVERBOSE'


if [[ -z $NUM_BLOCKS ]]; then
  echo "Must specify NUM_BLOCKS"
  exit 1
fi

if [[ -z $MATRIX_SIZE ]]; then
  echo "Must specify MATRIX_SIZE"
  exit 1
fi

export EXTRA_KERNEL_ARGS="-DNUM_BLOCKS=$NUM_BLOCKS -DMATRIX_SIZE=$MATRIX_SIZE -DVERBOSE"

export EXTRA_LINKER_ARGS='-lblas -llapack'
# export EXTRA_RUNTIME_ARGS='-DIARA_DISABLE_OMP -DIARA_DEBUGPRINT'
# export EXTRA_RUNTIME_ARGS='-DIARA_DISABLE_OMP'
# export EXTRA_RUNTIME_ARGS='-DIARA_DEBU'
