export EXTRA_KERNEL_ARGS='-DNUM_BLOCKS=4 -DMATRIX_SIZE=8192 -DVERBOSE'
export EXTRA_LINKER_ARGS='-lblas -llapack'
# export EXTRA_RUNTIME_ARGS='-DIARA_DISABLE_OMP -DIARA_DEBUGPRINT'
export EXTRA_RUNTIME_ARGS='-DIARA_DISABLE_OMP'
